/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrintTestKindRouteImport } from './routes/print-test.$kind'
import { Route as MenuTableCodeRouteImport } from './routes/menu.$tableCode'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppPosRouteImport } from './routes/_app/pos'
import { Route as AppMembersRouteImport } from './routes/_app/members'
import { Route as AppDetailVoidsRouteImport } from './routes/_app/detail-voids'
import { Route as AppDetailTipsRouteImport } from './routes/_app/detail-tips'
import { Route as AppDetailQrRouteImport } from './routes/_app/detail-qr'
import { Route as AppDetailGrossRouteImport } from './routes/_app/detail-gross'
import { Route as AppDetailDiscountsRouteImport } from './routes/_app/detail-discounts'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as ApiPublicQrOrderRouteImport } from './routes/api/public/qr-order'
import { Route as AppPaymentBillIdRouteImport } from './routes/_app/payment.$billId'
import { Route as AppOrderOrderIdRouteImport } from './routes/_app/order.$orderId'
import { Route as ApiPublicQrMenuTableCodeRouteImport } from './routes/api/public/qr-menu.$tableCode'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintTestKindRoute = PrintTestKindRouteImport.update({
  id: '/print-test/$kind',
  path: '/print-test/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuTableCodeRoute = MenuTableCodeRouteImport.update({
  id: '/menu/$tableCode',
  path: '/menu/$tableCode',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoute,
} as any)
const AppDetailVoidsRoute = AppDetailVoidsRouteImport.update({
  id: '/detail-voids',
  path: '/detail-voids',
  getParentRoute: () => AppRoute,
} as any)
const AppDetailTipsRoute = AppDetailTipsRouteImport.update({
  id: '/detail-tips',
  path: '/detail-tips',
  getParentRoute: () => AppRoute,
} as any)
const AppDetailQrRoute = AppDetailQrRouteImport.update({
  id: '/detail-qr',
  path: '/detail-qr',
  getParentRoute: () => AppRoute,
} as any)
const AppDetailGrossRoute = AppDetailGrossRouteImport.update({
  id: '/detail-gross',
  path: '/detail-gross',
  getParentRoute: () => AppRoute,
} as any)
const AppDetailDiscountsRoute = AppDetailDiscountsRouteImport.update({
  id: '/detail-discounts',
  path: '/detail-discounts',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicQrOrderRoute = ApiPublicQrOrderRouteImport.update({
  id: '/api/public/qr-order',
  path: '/api/public/qr-order',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPaymentBillIdRoute = AppPaymentBillIdRouteImport.update({
  id: '/payment/$billId',
  path: '/payment/$billId',
  getParentRoute: () => AppRoute,
} as any)
const AppOrderOrderIdRoute = AppOrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicQrMenuTableCodeRoute =
  ApiPublicQrMenuTableCodeRouteImport.update({
    id: '/api/public/qr-menu/$tableCode',
    path: '/api/public/qr-menu/$tableCode',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/detail-discounts': typeof AppDetailDiscountsRoute
  '/detail-gross': typeof AppDetailGrossRoute
  '/detail-qr': typeof AppDetailQrRoute
  '/detail-tips': typeof AppDetailTipsRoute
  '/detail-voids': typeof AppDetailVoidsRoute
  '/members': typeof AppMembersRoute
  '/pos': typeof AppPosRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/menu/$tableCode': typeof MenuTableCodeRoute
  '/print-test/$kind': typeof PrintTestKindRoute
  '/order/$orderId': typeof AppOrderOrderIdRoute
  '/payment/$billId': typeof AppPaymentBillIdRoute
  '/api/public/qr-order': typeof ApiPublicQrOrderRoute
  '/api/public/qr-menu/$tableCode': typeof ApiPublicQrMenuTableCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/detail-discounts': typeof AppDetailDiscountsRoute
  '/detail-gross': typeof AppDetailGrossRoute
  '/detail-qr': typeof AppDetailQrRoute
  '/detail-tips': typeof AppDetailTipsRoute
  '/detail-voids': typeof AppDetailVoidsRoute
  '/members': typeof AppMembersRoute
  '/pos': typeof AppPosRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/menu/$tableCode': typeof MenuTableCodeRoute
  '/print-test/$kind': typeof PrintTestKindRoute
  '/order/$orderId': typeof AppOrderOrderIdRoute
  '/payment/$billId': typeof AppPaymentBillIdRoute
  '/api/public/qr-order': typeof ApiPublicQrOrderRoute
  '/api/public/qr-menu/$tableCode': typeof ApiPublicQrMenuTableCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/detail-discounts': typeof AppDetailDiscountsRoute
  '/_app/detail-gross': typeof AppDetailGrossRoute
  '/_app/detail-qr': typeof AppDetailQrRoute
  '/_app/detail-tips': typeof AppDetailTipsRoute
  '/_app/detail-voids': typeof AppDetailVoidsRoute
  '/_app/members': typeof AppMembersRoute
  '/_app/pos': typeof AppPosRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/menu/$tableCode': typeof MenuTableCodeRoute
  '/print-test/$kind': typeof PrintTestKindRoute
  '/_app/order/$orderId': typeof AppOrderOrderIdRoute
  '/_app/payment/$billId': typeof AppPaymentBillIdRoute
  '/api/public/qr-order': typeof ApiPublicQrOrderRoute
  '/api/public/qr-menu/$tableCode': typeof ApiPublicQrMenuTableCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/detail-discounts'
    | '/detail-gross'
    | '/detail-qr'
    | '/detail-tips'
    | '/detail-voids'
    | '/members'
    | '/pos'
    | '/reports'
    | '/settings'
    | '/menu/$tableCode'
    | '/print-test/$kind'
    | '/order/$orderId'
    | '/payment/$billId'
    | '/api/public/qr-order'
    | '/api/public/qr-menu/$tableCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/detail-discounts'
    | '/detail-gross'
    | '/detail-qr'
    | '/detail-tips'
    | '/detail-voids'
    | '/members'
    | '/pos'
    | '/reports'
    | '/settings'
    | '/menu/$tableCode'
    | '/print-test/$kind'
    | '/order/$orderId'
    | '/payment/$billId'
    | '/api/public/qr-order'
    | '/api/public/qr-menu/$tableCode'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/_app/detail-discounts'
    | '/_app/detail-gross'
    | '/_app/detail-qr'
    | '/_app/detail-tips'
    | '/_app/detail-voids'
    | '/_app/members'
    | '/_app/pos'
    | '/_app/reports'
    | '/_app/settings'
    | '/menu/$tableCode'
    | '/print-test/$kind'
    | '/_app/order/$orderId'
    | '/_app/payment/$billId'
    | '/api/public/qr-order'
    | '/api/public/qr-menu/$tableCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  MenuTableCodeRoute: typeof MenuTableCodeRoute
  PrintTestKindRoute: typeof PrintTestKindRoute
  ApiPublicQrOrderRoute: typeof ApiPublicQrOrderRoute
  ApiPublicQrMenuTableCodeRoute: typeof ApiPublicQrMenuTableCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print-test/$kind': {
      id: '/print-test/$kind'
      path: '/print-test/$kind'
      fullPath: '/print-test/$kind'
      preLoaderRoute: typeof PrintTestKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/$tableCode': {
      id: '/menu/$tableCode'
      path: '/menu/$tableCode'
      fullPath: '/menu/$tableCode'
      preLoaderRoute: typeof MenuTableCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members': {
      id: '/_app/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/detail-voids': {
      id: '/_app/detail-voids'
      path: '/detail-voids'
      fullPath: '/detail-voids'
      preLoaderRoute: typeof AppDetailVoidsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/detail-tips': {
      id: '/_app/detail-tips'
      path: '/detail-tips'
      fullPath: '/detail-tips'
      preLoaderRoute: typeof AppDetailTipsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/detail-qr': {
      id: '/_app/detail-qr'
      path: '/detail-qr'
      fullPath: '/detail-qr'
      preLoaderRoute: typeof AppDetailQrRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/detail-gross': {
      id: '/_app/detail-gross'
      path: '/detail-gross'
      fullPath: '/detail-gross'
      preLoaderRoute: typeof AppDetailGrossRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/detail-discounts': {
      id: '/_app/detail-discounts'
      path: '/detail-discounts'
      fullPath: '/detail-discounts'
      preLoaderRoute: typeof AppDetailDiscountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/qr-order': {
      id: '/api/public/qr-order'
      path: '/api/public/qr-order'
      fullPath: '/api/public/qr-order'
      preLoaderRoute: typeof ApiPublicQrOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/payment/$billId': {
      id: '/_app/payment/$billId'
      path: '/payment/$billId'
      fullPath: '/payment/$billId'
      preLoaderRoute: typeof AppPaymentBillIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/order/$orderId': {
      id: '/_app/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof AppOrderOrderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/qr-menu/$tableCode': {
      id: '/api/public/qr-menu/$tableCode'
      path: '/api/public/qr-menu/$tableCode'
      fullPath: '/api/public/qr-menu/$tableCode'
      preLoaderRoute: typeof ApiPublicQrMenuTableCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppDetailDiscountsRoute: typeof AppDetailDiscountsRoute
  AppDetailGrossRoute: typeof AppDetailGrossRoute
  AppDetailQrRoute: typeof AppDetailQrRoute
  AppDetailTipsRoute: typeof AppDetailTipsRoute
  AppDetailVoidsRoute: typeof AppDetailVoidsRoute
  AppMembersRoute: typeof AppMembersRoute
  AppPosRoute: typeof AppPosRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppOrderOrderIdRoute: typeof AppOrderOrderIdRoute
  AppPaymentBillIdRoute: typeof AppPaymentBillIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppDetailDiscountsRoute: AppDetailDiscountsRoute,
  AppDetailGrossRoute: AppDetailGrossRoute,
  AppDetailQrRoute: AppDetailQrRoute,
  AppDetailTipsRoute: AppDetailTipsRoute,
  AppDetailVoidsRoute: AppDetailVoidsRoute,
  AppMembersRoute: AppMembersRoute,
  AppPosRoute: AppPosRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppOrderOrderIdRoute: AppOrderOrderIdRoute,
  AppPaymentBillIdRoute: AppPaymentBillIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  MenuTableCodeRoute: MenuTableCodeRoute,
  PrintTestKindRoute: PrintTestKindRoute,
  ApiPublicQrOrderRoute: ApiPublicQrOrderRoute,
  ApiPublicQrMenuTableCodeRoute: ApiPublicQrMenuTableCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
