/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MenuTableCodeRouteImport } from './routes/menu.$tableCode'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppPosRouteImport } from './routes/_app/pos'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as ApiPublicQrOrderRouteImport } from './routes/api/public/qr-order'
import { Route as AppPaymentBillIdRouteImport } from './routes/_app/payment.$billId'
import { Route as AppOrderOrderIdRouteImport } from './routes/_app/order.$orderId'
import { Route as ApiPublicQrMenuTableCodeRouteImport } from './routes/api/public/qr-menu.$tableCode'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuTableCodeRoute = MenuTableCodeRouteImport.update({
  id: '/menu/$tableCode',
  path: '/menu/$tableCode',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicQrOrderRoute = ApiPublicQrOrderRouteImport.update({
  id: '/api/public/qr-order',
  path: '/api/public/qr-order',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPaymentBillIdRoute = AppPaymentBillIdRouteImport.update({
  id: '/payment/$billId',
  path: '/payment/$billId',
  getParentRoute: () => AppRoute,
} as any)
const AppOrderOrderIdRoute = AppOrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicQrMenuTableCodeRoute =
  ApiPublicQrMenuTableCodeRouteImport.update({
    id: '/api/public/qr-menu/$tableCode',
    path: '/api/public/qr-menu/$tableCode',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/pos': typeof AppPosRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/menu/$tableCode': typeof MenuTableCodeRoute
  '/order/$orderId': typeof AppOrderOrderIdRoute
  '/payment/$billId': typeof AppPaymentBillIdRoute
  '/api/public/qr-order': typeof ApiPublicQrOrderRoute
  '/api/public/qr-menu/$tableCode': typeof ApiPublicQrMenuTableCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/pos': typeof AppPosRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/menu/$tableCode': typeof MenuTableCodeRoute
  '/order/$orderId': typeof AppOrderOrderIdRoute
  '/payment/$billId': typeof AppPaymentBillIdRoute
  '/api/public/qr-order': typeof ApiPublicQrOrderRoute
  '/api/public/qr-menu/$tableCode': typeof ApiPublicQrMenuTableCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/pos': typeof AppPosRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/menu/$tableCode': typeof MenuTableCodeRoute
  '/_app/order/$orderId': typeof AppOrderOrderIdRoute
  '/_app/payment/$billId': typeof AppPaymentBillIdRoute
  '/api/public/qr-order': typeof ApiPublicQrOrderRoute
  '/api/public/qr-menu/$tableCode': typeof ApiPublicQrMenuTableCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/pos'
    | '/reports'
    | '/settings'
    | '/menu/$tableCode'
    | '/order/$orderId'
    | '/payment/$billId'
    | '/api/public/qr-order'
    | '/api/public/qr-menu/$tableCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/pos'
    | '/reports'
    | '/settings'
    | '/menu/$tableCode'
    | '/order/$orderId'
    | '/payment/$billId'
    | '/api/public/qr-order'
    | '/api/public/qr-menu/$tableCode'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/_app/pos'
    | '/_app/reports'
    | '/_app/settings'
    | '/menu/$tableCode'
    | '/_app/order/$orderId'
    | '/_app/payment/$billId'
    | '/api/public/qr-order'
    | '/api/public/qr-menu/$tableCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  MenuTableCodeRoute: typeof MenuTableCodeRoute
  ApiPublicQrOrderRoute: typeof ApiPublicQrOrderRoute
  ApiPublicQrMenuTableCodeRoute: typeof ApiPublicQrMenuTableCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/$tableCode': {
      id: '/menu/$tableCode'
      path: '/menu/$tableCode'
      fullPath: '/menu/$tableCode'
      preLoaderRoute: typeof MenuTableCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/qr-order': {
      id: '/api/public/qr-order'
      path: '/api/public/qr-order'
      fullPath: '/api/public/qr-order'
      preLoaderRoute: typeof ApiPublicQrOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/payment/$billId': {
      id: '/_app/payment/$billId'
      path: '/payment/$billId'
      fullPath: '/payment/$billId'
      preLoaderRoute: typeof AppPaymentBillIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/order/$orderId': {
      id: '/_app/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof AppOrderOrderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/qr-menu/$tableCode': {
      id: '/api/public/qr-menu/$tableCode'
      path: '/api/public/qr-menu/$tableCode'
      fullPath: '/api/public/qr-menu/$tableCode'
      preLoaderRoute: typeof ApiPublicQrMenuTableCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppPosRoute: typeof AppPosRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppOrderOrderIdRoute: typeof AppOrderOrderIdRoute
  AppPaymentBillIdRoute: typeof AppPaymentBillIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppPosRoute: AppPosRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppOrderOrderIdRoute: AppOrderOrderIdRoute,
  AppPaymentBillIdRoute: AppPaymentBillIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  MenuTableCodeRoute: MenuTableCodeRoute,
  ApiPublicQrOrderRoute: ApiPublicQrOrderRoute,
  ApiPublicQrMenuTableCodeRoute: ApiPublicQrMenuTableCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
